FROM golang:1.25-bookworm AS builder

ARG MINIO_VERSION=RELEASE.2025-09-07T16-13-09Z

RUN CGO_ENABLED=0 GOBIN=/out \
    go install github.com/minio/minio@${MINIO_VERSION}

FROM debian:bookworm-slim

COPY --from=builder /out/minio /usr/local/bin/minio

VOLUME ["/data"]
EXPOSE 9000 9001

ENTRYPOINT ["minio"]
CMD ["server", "/data", "--console-address", ":9001"]
