# Generated by Django 6.1.2 on 2026-10-06 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeospatialFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('SHAPEFILE', 'Shapefile'), ('KML', 'KML')], max_length=20)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=20)),
                ('source_crs', models.CharField(blank=True, max_length=255, null=True)),
                ('measurement_crs', models.CharField(blank=True, max_length=255, null=True)),
                ('feature_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_index', models.PositiveIntegerField()),
                ('geometry_type', models.CharField(max_length=50)),
                ('geometry', models.JSONField()),
                ('properties', models.JSONField(default=dict)),
                ('measurement_type', models.CharField(blank=True, choices=[('AREA', 'Area'), ('LENGTH', 'Length')], max_length=20, null=True)),
                ('measurement_value', models.FloatField(blank=True, null=True)),
                ('measurement_status', models.CharField(choices=[('CALCULATED', 'Calculated'), ('NOT_REQUIRED', 'Not required'), ('UNSUPPORTED', 'Unsupported')], max_length=20)),
                ('geospatial_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='geofiles.geospatialfile')),
            ],
            options={
                'ordering': ['feature_index'],
                'constraints': [models.UniqueConstraint(fields=('geospatial_file', 'feature_index'), name='unique_feature_index_per_file')],
            },
        ),
    ]
