# Generated by Django 6.1.2 on 2026-10-06 18:05

import geofiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geospatialfile',
            name='file',
            field=models.FileField(upload_to=geofiles.models.geospatial_file_upload_path),
        ),
    ]
